// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWC3IlfjJYxGdr3epRgYJNmOORXLzEKoI',
    appId: '1:357266245281:web:ef581649b11cb670b7d2e0',
    messagingSenderId: '357266245281',
    projectId: 'ltnhungnhomanhtuan',
    authDomain: 'ltnhungnhomanhtuan.firebaseapp.com',
    storageBucket: 'ltnhungnhomanhtuan.firebasestorage.app',
    measurementId: 'G-81KRZ4E6DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9BX1OwHhOcKPRHJfPX_dxeVNKA9PV2cI',
    appId: '1:357266245281:android:b6aa505e9cf1a581b7d2e0',
    messagingSenderId: '357266245281',
    projectId: 'ltnhungnhomanhtuan',
    storageBucket: 'ltnhungnhomanhtuan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-lFkMol0WEmFDzgVgAP_xjKsmXq3k3g',
    appId: '1:357266245281:ios:30dd7eaf1a12c962b7d2e0',
    messagingSenderId: '357266245281',
    projectId: 'ltnhungnhomanhtuan',
    storageBucket: 'ltnhungnhomanhtuan.firebasestorage.app',
    iosBundleId: 'com.example.dieukhienthietbi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu-lFkMol0WEmFDzgVgAP_xjKsmXq3k3g',
    appId: '1:357266245281:ios:30dd7eaf1a12c962b7d2e0',
    messagingSenderId: '357266245281',
    projectId: 'ltnhungnhomanhtuan',
    storageBucket: 'ltnhungnhomanhtuan.firebasestorage.app',
    iosBundleId: 'com.example.dieukhienthietbi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWC3IlfjJYxGdr3epRgYJNmOORXLzEKoI',
    appId: '1:357266245281:web:239aedddac14e15bb7d2e0',
    messagingSenderId: '357266245281',
    projectId: 'ltnhungnhomanhtuan',
    authDomain: 'ltnhungnhomanhtuan.firebaseapp.com',
    storageBucket: 'ltnhungnhomanhtuan.firebasestorage.app',
    measurementId: 'G-8TM8KT758H',
  );

}